# Generated by Django 4.2.13 on 2024-08-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taxes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ComplianceCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_compliant", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compliance.compliancerule",
                    ),
                ),
                (
                    "tax_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxes.taxrecord",
                    ),
                ),
            ],
        ),
    ]
