# Generated by Django 4.2.13 on 2024-08-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taxes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_file", models.FileField(upload_to="reports/")),
                ("date_generated", models.DateTimeField(auto_now_add=True)),
                (
                    "tax_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxes.taxrecord",
                    ),
                ),
            ],
        ),
    ]
